/**
 * miyabi:todos - TODO コメント検出 → Issue自動作成
 *
 * Usage: npm run miyabi:todos
 */

import { Logger } from '../utils/logger.js';

const logger = new Logger('MiyabiTodos');

interface TodoItem {
  file: string;
  line: number;
  text: string;
}

function formatTodoAsIssueBody(todo: TodoItem): string {
  return [
    `## TODO detected`,
    '',
    `**File**: \`${todo.file}:${todo.line}\``,
    `**Content**: ${todo.text}`,
    '',
    '---',
    'Auto-generated by miyabi:todos',
  ].join('\n');
}

async function main(): Promise<void> {
  logger.info('Scanning for TODO comments...');

  // TODO: Implement actual scanning
  // 1. grep -rn "TODO\|FIXME\|HACK\|XXX" src/ tests/
  // 2. Parse results into TodoItem[]
  // 3. Check existing issues to avoid duplicates
  // 4. Create new issues via gh issue create

  // formatTodoAsIssueBody will be used when scanning is implemented
  void formatTodoAsIssueBody;
  logger.info('TODO scanning not yet implemented. Use /miyabi-todos in Claude Code.');
}

main().catch((error: unknown) => {
  logger.error('TODO scan failed', { error: String(error) });
  process.exit(1);
});
